name: knowyourself
description: KYB - Physical & Mental Health Tracker is a comprehensive app that helps you track your overall well-being. With KYB, you can write journals, create to-do lists, and celebrate your accomplishments, all in one place.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.6

#  flutter_screenutil: ^5.9.0
  path_provider: ^2.1.2
  share_plus: ^8.0.2
  file_picker: ^8.0.0+1
  local_auth: ^2.2.0

  permission_handler: ^11.3.1
  awesome_notifications: ^0.9.3+1
  workmanager:
  cached_network_image:

  flutter_svg: ^2.0.10+1
  google_fonts: ^6.2.1
  intl: ^0.19.0

  smooth_page_indicator: ^1.1.0
  table_calendar: ^3.1.1
  timezone: ^0.9.2
  url_launcher: ^6.2.5

  http: ^1.2.1
  html: ^0.15.4

  firebase_auth: ^4.19.0
  firebase_core: ^2.28.0
  cloud_firestore: ^4.16.0
  firebase_storage: ^11.7.0
  animated_emoji: ^3.1.0

  get: ^4.6.6
  get_storage: ^2.1.1
  google_sign_in: ^6.2.1
  lottie: ^3.1.0

  image_picker: ^1.0.7
  geolocator: ^11.0.0
  geocoding:
  tflite_flutter: ^0.10.4
  firebase_ml_model_downloader: ^0.2.4+16

#
#dependency_overrides:
#  google_fonts: ^6.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.2

flutter:
  uses-material-design: true

  assets:
    - assets/emojis/
    - assets/illustrations/
    - assets/avatars/
    - assets/brand/
    - assets/icons/
    - assets/animations/
    - assets/materials/
    - assets/mood_shifter/
    - assets/mood_shifter/mood_shift.tflite
    - assets/mood_shifter/emotions.json
    - assets/mood_shifter/sentiments.json
    - assets/mood_shifter/updated_activities.json
    - assets/value_analysis/value_analysis.tflite
    - assets/value_analysis/core_values.txt
    - assets/value_analysis/journal_entries.txt
    - assets/chapters/
    - packages/animated_emoji/lottie/sad.json
    - packages/animated_emoji/lottie/grin.json
    - packages/animated_emoji/lottie/anxiousWithSweat.json
    - packages/animated_emoji/lottie/surprised.json
    - packages/animated_emoji/lottie/rage.json
    - packages/animated_emoji/lottie/distraught.json
    - packages/animated_emoji/lottie/cry.json
    - packages/animated_emoji/lottie/sweat.json
    - packages/animated_emoji/lottie/grinning.json
    - packages/animated_emoji/lottie/pleading.json
    - packages/animated_emoji/lottie/scared.json
